//! Python 代码生成器

use std::fs;
use std::path::Path;

use crate::error::{CompileError, CompileResult};
use crate::schema::EquationFile;

/// Python 代码生成器
pub struct PythonGenerator;

impl PythonGenerator {
    /// 生成 Python 代码
    pub fn generate(files: &[EquationFile], output_dir: &Path) -> CompileResult<()> {
        fs::create_dir_all(output_dir).map_err(|e| CompileError::io(output_dir, e))?;

        // 生成 __init__.py
        let init_content = Self::generate_init(files);
        fs::write(output_dir.join("__init__.py"), init_content)
            .map_err(|e| CompileError::io(output_dir.join("__init__.py"), e))?;

        // 生成每个模块的文件
        for file in files {
            let module_name = file.meta.id.to_lowercase();
            let content = Self::generate_module(file);
            let file_path = output_dir.join(format!("{}.py", module_name));
            fs::write(&file_path, content).map_err(|e| CompileError::io(&file_path, e))?;

            // 动态模型：额外生成可独立运行的逐日仿真器（与 eqc simulate 同语义）
            if let Some(sim_code) = super::python_sim::generate_python_simulator(file) {
                let sim_path = output_dir.join(format!("{}_sim.py", module_name));
                fs::write(&sim_path, sim_code).map_err(|e| CompileError::io(&sim_path, e))?;
            }
        }

        // 生成参数文件
        let params_content = Self::generate_params(files);
        fs::write(output_dir.join("params.py"), params_content)
            .map_err(|e| CompileError::io(output_dir.join("params.py"), e))?;

        Ok(())
    }

    fn generate_init(files: &[EquationFile]) -> String {
        let mut lines = vec![
            "# 自动生成的代码，请勿手动编辑".to_string(),
            "# Generated by equation-compiler".to_string(),
            "".to_string(),
        ];

        for file in files {
            let module_name = file.meta.id.to_lowercase();
            lines.push(format!("from .{} import *", module_name));
        }

        lines.push("from .params import *".to_string());
        lines.join("\n")
    }

    fn generate_module(file: &EquationFile) -> String {
        let mut lines = vec![
            format!("# {}", file.meta.name_cn),
            format!("# 模块: {} ({})", file.meta.id, file.meta.model),
            "# 自动生成的代码，请勿手动编辑".to_string(),
            "".to_string(),
            "from dataclasses import dataclass".to_string(),
            "import numpy as np".to_string(),
            "".to_string(),
            format!("from .params import {}Params", file.meta.id),
            "".to_string(),
        ];

        // 生成每个方程的函数
        for eq in &file.equations {
            lines.push(Self::generate_equation_function(file, eq));
            lines.push("".to_string());
        }

        lines.join("\n")
    }

    fn generate_equation_function(
        file: &EquationFile,
        eq: &crate::schema::Equation,
    ) -> String {
        let func_name = eq.id.to_lowercase().replace('-', "_");
        let params_type = format!("{}Params", file.meta.id);

        // 收集输入参数
        let var_refs = eq.get_variable_refs();
        let mut args: Vec<String> = var_refs.iter().map(|v| format!("{}: float", v)).collect();
        args.push(format!("params: {}", params_type));

        let args_str = args.join(", ");

        // 生成函数体
        let body = eq.expression.to_python("params");

        let mut lines = vec![
            format!("def {}({}) -> float:", func_name, args_str),
            format!("    \"\"\""),
            format!("    {}: {}", eq.id, eq.name),
        ];

        if let Some(ref formula) = eq.formula_display {
            lines.push("    ".to_string());
            lines.push(format!("    公式: {}", formula));
        }

        if let Some(ref reference) = eq.reference {
            lines.push("    ".to_string());
            lines.push(format!("    参考: {}", reference));
        }

        lines.push("    \"\"\"".to_string());
        lines.push(format!("    return {}", body));

        lines.join("\n")
    }

    fn generate_params(files: &[EquationFile]) -> String {
        let mut lines = vec![
            "# 参数定义".to_string(),
            "# 自动生成的代码，请勿手动编辑".to_string(),
            "".to_string(),
            "from dataclasses import dataclass".to_string(),
            "".to_string(),
        ];

        for file in files {
            lines.push("@dataclass".to_string());
            lines.push(format!("class {}Params:", file.meta.id));
            lines.push(format!("    \"\"\"{}模块参数\"\"\"", file.meta.name_cn));

            for (name, param) in &file.parameters {
                let comment = if let Some(ref unit) = param.unit {
                    format!("  # {} [{}]", param.name_cn, unit)
                } else {
                    format!("  # {}", param.name_cn)
                };
                lines.push(format!("    {}: float = {}{}", name, param.default, comment));
            }

            lines.push("".to_string());
        }

        lines.join("\n")
    }
}
