//! Rust 算子代码生成器
//!
//! 生成与 lowcode 平台兼容的 Rust 算子代码。

use std::fs;
use std::path::Path;

use crate::error::{CompileError, CompileResult};
use crate::schema::EquationFile;

/// Rust 算子代码生成器
pub struct RustOperatorGenerator;

impl RustOperatorGenerator {
    /// 生成 Rust 算子代码
    pub fn generate(files: &[EquationFile], output_dir: &Path) -> CompileResult<()> {
        fs::create_dir_all(output_dir).map_err(|e| CompileError::io(output_dir, e))?;

        // 生成 mod.rs
        let mod_content = Self::generate_mod(files);
        fs::write(output_dir.join("mod.rs"), mod_content)
            .map_err(|e| CompileError::io(output_dir.join("mod.rs"), e))?;

        // 生成每个模块的文件
        for file in files {
            let module_name = file.meta.id.to_lowercase();
            let content = Self::generate_module(file);
            let file_path = output_dir.join(format!("{}.rs", module_name));
            fs::write(&file_path, content).map_err(|e| CompileError::io(&file_path, e))?;
        }

        Ok(())
    }

    fn generate_mod(files: &[EquationFile]) -> String {
        let mut lines = vec![
            "//! 自动生成的算子代码".to_string(),
            "//! Generated by equation-compiler".to_string(),
            "".to_string(),
        ];

        for file in files {
            let module_name = file.meta.id.to_lowercase();
            lines.push(format!("pub mod {};", module_name));
        }

        lines.push("".to_string());
        lines.push("use crate::lowcode::registry::OperatorRegistryBuilder;".to_string());
        lines.push("".to_string());
        lines.push("/// 注册所有生成的算子".to_string());
        lines.push(
            "pub fn register_all(builder: OperatorRegistryBuilder) -> OperatorRegistryBuilder {"
                .to_string(),
        );
        lines.push("    builder".to_string());

        for file in files {
            let module_name = file.meta.id.to_lowercase();
            for eq in &file.equations {
                let struct_name = Self::to_struct_name(&eq.id);
                lines.push(format!(
                    "        .register(Box::new({}::{}Operator))",
                    module_name, struct_name
                ));
            }
        }

        lines.push("}".to_string());
        lines.join("\n")
    }

    fn generate_module(file: &EquationFile) -> String {
        let mut lines = vec![
            format!("//! {} ({})", file.meta.name_cn, file.meta.id),
            format!("//! 模型: {}", file.meta.model),
            "//! 自动生成的代码，请勿手动编辑".to_string(),
            "".to_string(),
            "use crate::lowcode::core::metadata::{InputDef, OutputDef};".to_string(),
            "use crate::lowcode::core::types::DataType;".to_string(),
            "use crate::lowcode::core::{LowcodeError, Operator, OperatorMetadata};".to_string(),
            "use serde_json::{json, Value};".to_string(),
            "".to_string(),
        ];

        // 生成每个方程的算子
        for eq in &file.equations {
            lines.push(Self::generate_operator(file, eq));
            lines.push("".to_string());
        }

        lines.join("\n")
    }

    fn generate_operator(file: &EquationFile, eq: &crate::schema::Equation) -> String {
        let struct_name = format!("{}Operator", Self::to_struct_name(&eq.id));
        let operator_id = format!(
            "{}.{}",
            file.meta.id.to_lowercase(),
            eq.id.to_lowercase().replace('-', "_")
        );

        // 收集输入端口
        let var_refs = eq.get_variable_refs();
        let param_refs = eq.get_parameter_refs();

        // 生成 InputDef
        let mut input_defs = Vec::new();
        for var in &var_refs {
            let desc = file
                .variables
                .get(var)
                .and_then(|v| v.description.as_ref())
                .map(|d| format!(".with_description(\"{}\")", d))
                .unwrap_or_default();
            input_defs.push(format!(
                "            .input(InputDef::required(\"{}\", DataType::Number){})",
                var, desc
            ));
        }
        for param in &param_refs {
            if let Some(p) = file.parameters.get(param) {
                // 获取默认值（确保是浮点格式）
                let default_val = if p.default.fract() == 0.0 {
                    format!("{:.1}", p.default)  // 1 -> 1.0
                } else {
                    format!("{}", p.default)
                };
                let with_default = format!(".with_default(json!({}))", default_val);
                input_defs.push(format!(
                    "            .input(InputDef::optional(\"{}\", DataType::Number).with_description(\"{}\"){})",
                    param, p.name_cn, with_default
                ));
            } else {
                input_defs.push(format!(
                    "            .input(InputDef::required(\"{}\", DataType::Number))",
                    param
                ));
            }
        }
        let inputs_str = input_defs.join("\n");

        // 生成执行逻辑 - 提取变量
        let mut get_vars = Vec::new();
        for var in &var_refs {
            get_vars.push(format!(
                r#"        let {var} = input
            .get("{var}")
            .and_then(|v| v.as_f64())
            .ok_or_else(|| LowcodeError::MissingRequiredField("{var}".into()))?;"#,
                var = var
            ));
        }
        for param in &param_refs {
            // 参数有默认值（确保是浮点格式）
            if let Some(p) = file.parameters.get(param) {
                let default_val = if p.default.fract() == 0.0 {
                    format!("{:.1}", p.default)  // 1 -> 1.0
                } else {
                    format!("{}", p.default)
                };
                get_vars.push(format!(
                    r#"        let {param} = input
            .get("{param}")
            .and_then(|v| v.as_f64())
            .unwrap_or({default});"#,
                    param = param,
                    default = default_val
                ));
            } else {
                get_vars.push(format!(
                    r#"        let {param} = input
            .get("{param}")
            .and_then(|v| v.as_f64())
            .ok_or_else(|| LowcodeError::MissingRequiredField("{param}".into()))?;"#,
                    param = param
                ));
            }
        }
        let get_vars_str = get_vars.join("\n\n");

        // 使用强类型 AST 的 to_rust() 方法生成计算表达式
        let expr_rust = Self::strip_outer_parens(&eq.expression.to_rust());

        // 处理公式注释
        let formula_comment = eq
            .formula_display
            .as_ref()
            .map(|f| format!("///\n/// 公式: `{}`", f))
            .unwrap_or_default();

        format!(
            r#"/// {name}
///
/// 方程 ID: `{eq_id}`
{formula_comment}
pub struct {struct_name};

impl Operator for {struct_name} {{
    fn metadata(&self) -> OperatorMetadata {{
        OperatorMetadata::builder("{operator_id}", "{name}")
            .category("{category}")
            .description("{description}")
            .version("1.0.0")
{inputs_str}
            .output(OutputDef::new("{output}", DataType::Number).with_description("{output_desc} 输出"))
            .build()
    }}

    fn execute(&self, input: Value) -> Result<Value, LowcodeError> {{
{get_vars_str}

        let result = {expr_rust};

        Ok(json!({{ "{output}": result }}))
    }}
}}"#,
            name = eq.name,
            eq_id = eq.id,
            formula_comment = formula_comment,
            struct_name = struct_name,
            operator_id = operator_id,
            category = file.meta.id.to_lowercase(),
            description = file
                .meta
                .description
                .as_deref()
                .unwrap_or(&eq.name),
            inputs_str = inputs_str,
            output = eq.output,
            output_desc = eq.name,
            get_vars_str = get_vars_str,
            expr_rust = expr_rust,
        )
    }

    fn to_struct_name(id: &str) -> String {
        // damped_oscillation -> DampedOscillation
        // PHOTO-01 -> Photo01
        id.split(['-', '_'])
            .map(|part| {
                let mut chars = part.chars();
                match chars.next() {
                    None => String::new(),
                    Some(c) => {
                        c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase()
                    }
                }
            })
            .collect()
    }

    /// 去除最外层多余的括号，避免 Clippy 警告
    fn strip_outer_parens(s: &str) -> String {
        let s = s.trim();
        if s.starts_with('(') && s.ends_with(')') {
            // 检查括号是否匹配（避免移除 (a) + (b) 这种情况的括号）
            let inner = &s[1..s.len() - 1];
            let mut depth = 0;
            let mut balanced = true;
            for c in inner.chars() {
                match c {
                    '(' => depth += 1,
                    ')' => {
                        depth -= 1;
                        if depth < 0 {
                            balanced = false;
                            break;
                        }
                    }
                    _ => {}
                }
            }
            if balanced && depth == 0 {
                return inner.to_string();
            }
        }
        s.to_string()
    }
}
