//! 自动生成的算子代码
//! Generated by equation-compiler

pub mod cascade;
pub mod math_demo;
pub mod photo;

use crate::lowcode::registry::OperatorRegistryBuilder;

/// 注册所有生成的算子
pub fn register_all(builder: OperatorRegistryBuilder) -> OperatorRegistryBuilder {
    builder
        .register(Box::new(cascade::Stage1Operator))
        .register(Box::new(cascade::Stage2Operator))
        .register(Box::new(cascade::Stage3Operator))
        .register(Box::new(math_demo::DampedOscillationOperator))
        .register(Box::new(math_demo::TanhActivationOperator))
        .register(Box::new(math_demo::AngleCalcOperator))
        .register(Box::new(math_demo::RoundingDemoOperator))
        .register(Box::new(math_demo::SignAbsDemoOperator))
        .register(Box::new(math_demo::RootLogDemoOperator))
        .register(Box::new(math_demo::ReluActivationOperator))
        .register(Box::new(math_demo::ModuloDemoOperator))
        .register(Box::new(math_demo::InverseTrigOperator))
        .register(Box::new(math_demo::ExpGrowthOperator))
        .register(Box::new(photo::Photo01Operator))
        .register(Box::new(photo::Photo02Operator))
}